### ISSUE TITLE
Lock Guides must be off for this to work

### ISSUE THREAD

**Issue by cjdunn** [ryanbugden/Edit-Font-Dimensions#1]
Hey Ryan, just a heads up that you need to turn off "Lock Guides" for this extension to work. 

Perhaps you can have your extension temporarily turn this setting off while it is active and return it to the previous state afterwards. The code looks like:
```
from mojo.UI import setDefault
#turn off Lock Guides
setDefault("glyphViewLockGuides", False)


#turn on Lock Guides
setDefault("glyphViewLockGuides", True)
```

Then return the user's Lock Guides setting to the original value once the tool is inactive. You can check using: 
from mojo.UI import getDefault
getDefault("glyphViewLockGuides")

If you're not able to do this, I can take a crack at is and send you a PR when I have more time. Hope this is helpful!

**Comment by ryanbugden** [comment]
Thanks! Let me know how this works out for you

**Comment by cjdunn** [comment]
@ryanbugden that works, thanks for the quick fix! 

Also, just a heads up that you have a .DS_Store file in your git commit history, which can cause issues down the road (especially when collaborating with others, etc). I'd recommend adding a global git ignore for .DS_store so it will never be committed to any of your repos, and remove it from your existing repos (not urgent, but just good to do at some point), see here: 
https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository

Thanks again for the excellent extension, it came is super handy for the project I'm working on today : )
